# coding: utf-8

# flake8: noqa
"""
    NGenetzky's API

    This is an API I am designing for myself using swagger. You can find  out more about Swagger at [http://swagger.io](http://swagger.io)   # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: Nathan@Genetzky.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from jatdb_client.models.trello_action import TrelloAction
from jatdb_client.models.trello_query import TrelloQuery
from jatdb_client.models.universal_resource import UniversalResource
