# coding: utf-8

# flake8: noqa
"""
    jatdb

    JSON API to DB: Fetch JSON from APIs and send to a TinyDB database.  # noqa: E501

    OpenAPI spec version: 0.0.2
    Contact: Nathan@Genetzky.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from jatdb_client.models.content_file import ContentFile
from jatdb_client.models.trello_action import TrelloAction
from jatdb_client.models.trello_query import TrelloQuery
from jatdb_client.models.universal_resource import UniversalResource
