# coding: utf-8

"""
    NGenetzky's API

    This is an API I am designing for myself using swagger. You can find  out more about Swagger at [http://swagger.io](http://swagger.io)   # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: Nathan@Genetzky.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TrelloQuery(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uri': 'str',
        'query_append': 'str'
    }

    attribute_map = {
        'uri': 'uri',
        'query_append': 'query_append'
    }

    def __init__(self, uri=None, query_append=None):  # noqa: E501
        """TrelloQuery - a model defined in Swagger"""  # noqa: E501

        self._uri = None
        self._query_append = None
        self.discriminator = None

        if uri is not None:
            self.uri = uri
        if query_append is not None:
            self.query_append = query_append

    @property
    def uri(self):
        """Gets the uri of this TrelloQuery.  # noqa: E501


        :return: The uri of this TrelloQuery.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this TrelloQuery.


        :param uri: The uri of this TrelloQuery.  # noqa: E501
        :type: str
        """

        self._uri = uri

    @property
    def query_append(self):
        """Gets the query_append of this TrelloQuery.  # noqa: E501

        Extra query information  # noqa: E501

        :return: The query_append of this TrelloQuery.  # noqa: E501
        :rtype: str
        """
        return self._query_append

    @query_append.setter
    def query_append(self, query_append):
        """Sets the query_append of this TrelloQuery.

        Extra query information  # noqa: E501

        :param query_append: The query_append of this TrelloQuery.  # noqa: E501
        :type: str
        """

        self._query_append = query_append

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrelloQuery):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
