# coding: utf-8

"""
    jatdb

    JSON API to DB: Fetch JSON from APIs and send to a TinyDB database.  # noqa: E501

    OpenAPI spec version: 0.0.2
    Contact: Nathan@Genetzky.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TrelloAction(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'data': 'object',
        'date': 'datetime',
        'id_member_creator': 'str',
        'type': 'str'
    }

    attribute_map = {
        'id': 'id',
        'data': 'data',
        'date': 'date',
        'id_member_creator': 'idMemberCreator',
        'type': 'type'
    }

    def __init__(self, id=None, data=None, date=None, id_member_creator=None, type=None):  # noqa: E501
        """TrelloAction - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._data = None
        self._date = None
        self._id_member_creator = None
        self._type = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if data is not None:
            self.data = data
        if date is not None:
            self.date = date
        if id_member_creator is not None:
            self.id_member_creator = id_member_creator
        if type is not None:
            self.type = type

    @property
    def id(self):
        """Gets the id of this TrelloAction.  # noqa: E501

        The ID of the action  # noqa: E501

        :return: The id of this TrelloAction.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TrelloAction.

        The ID of the action  # noqa: E501

        :param id: The id of this TrelloAction.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def data(self):
        """Gets the data of this TrelloAction.  # noqa: E501

        Relevant information regarding the action  # noqa: E501

        :return: The data of this TrelloAction.  # noqa: E501
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this TrelloAction.

        Relevant information regarding the action  # noqa: E501

        :param data: The data of this TrelloAction.  # noqa: E501
        :type: object
        """

        self._data = data

    @property
    def date(self):
        """Gets the date of this TrelloAction.  # noqa: E501

        When the action occurred  # noqa: E501

        :return: The date of this TrelloAction.  # noqa: E501
        :rtype: datetime
        """
        return self._date

    @date.setter
    def date(self, date):
        """Sets the date of this TrelloAction.

        When the action occurred  # noqa: E501

        :param date: The date of this TrelloAction.  # noqa: E501
        :type: datetime
        """

        self._date = date

    @property
    def id_member_creator(self):
        """Gets the id_member_creator of this TrelloAction.  # noqa: E501

        The ID of the member who caused the action  # noqa: E501

        :return: The id_member_creator of this TrelloAction.  # noqa: E501
        :rtype: str
        """
        return self._id_member_creator

    @id_member_creator.setter
    def id_member_creator(self, id_member_creator):
        """Sets the id_member_creator of this TrelloAction.

        The ID of the member who caused the action  # noqa: E501

        :param id_member_creator: The id_member_creator of this TrelloAction.  # noqa: E501
        :type: str
        """

        self._id_member_creator = id_member_creator

    @property
    def type(self):
        """Gets the type of this TrelloAction.  # noqa: E501

        The type of the action. See list of Action Types for options.  # noqa: E501

        :return: The type of this TrelloAction.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TrelloAction.

        The type of the action. See list of Action Types for options.  # noqa: E501

        :param type: The type of this TrelloAction.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrelloAction):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
