# coding: utf-8

"""
    NGenetzky's API

    This is an API I am designing for myself using swagger. You can find  out more about Swagger at [http://swagger.io](http://swagger.io)   # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: Nathan@Genetzky.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import jatdb_client
from jatdb_client.api.default_api import DefaultApi  # noqa: E501
from jatdb_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = jatdb_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_uri_post(self):
        """Test case for uri_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
