# coding: utf-8

"""
    NGenetzky's API

    This is an API I am designing for myself using swagger. You can find  out more about Swagger at [http://swagger.io](http://swagger.io)   # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: Nathan@Genetzky.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import jatdb_client
from jatdb_client.models.trello_query import TrelloQuery  # noqa: E501
from jatdb_client.rest import ApiException


class TestTrelloQuery(unittest.TestCase):
    """TrelloQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrelloQuery(self):
        """Test TrelloQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = jatdb_client.models.trello_query.TrelloQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
