# coding: utf-8

"""
    jatdb

    JSON API to DB: Fetch JSON from APIs and send to a TinyDB database.  # noqa: E501

    OpenAPI spec version: 0.0.2
    Contact: Nathan@Genetzky.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import jatdb_client
from jatdb_client.models.content_file import ContentFile  # noqa: E501
from jatdb_client.rest import ApiException


class TestContentFile(unittest.TestCase):
    """ContentFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContentFile(self):
        """Test ContentFile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = jatdb_client.models.content_file.ContentFile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
