# coding: utf-8

"""
    jatdb

    JSON API to DB: Fetch JSON from APIs and send to a TinyDB database.  # noqa: E501

    OpenAPI spec version: 0.0.2
    Contact: Nathan@Genetzky.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import jatdb_client
from jatdb_client.models.trello_action import TrelloAction  # noqa: E501
from jatdb_client.rest import ApiException


class TestTrelloAction(unittest.TestCase):
    """TrelloAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrelloAction(self):
        """Test TrelloAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = jatdb_client.models.trello_action.TrelloAction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
