# coding: utf-8

"""
    jatdb

    JSON API to DB: Fetch JSON from APIs and send to a TinyDB database.  # noqa: E501

    OpenAPI spec version: 0.0.2
    Contact: Nathan@Genetzky.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import jatdb_client
from jatdb_client.api.default_api import DefaultApi  # noqa: E501
from jatdb_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = jatdb_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_uri_post(self):
        """Test case for uri_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
