# coding: utf-8

"""
    jatdb

    JSON API to DB: Fetch JSON from APIs and send to a TinyDB database.  # noqa: E501

    OpenAPI spec version: 0.0.2
    Contact: Nathan@Genetzky.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import jatdb_client
from jatdb_client.api.content_api import ContentApi  # noqa: E501
from jatdb_client.rest import ApiException


class TestContentApi(unittest.TestCase):
    """ContentApi unit test stubs"""

    def setUp(self):
        self.api = jatdb_client.api.content_api.ContentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_content_get(self):
        """Test case for content_get

        """
        pass

    def test_content_post(self):
        """Test case for content_post

        """
        pass

    def test_content_put(self):
        """Test case for content_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
